kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pods-r
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch","pods/portforward"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: port-forward
rules:
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["get", "list", "create"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]